name: Verify Codebase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detekt:
    name: Check code base with detekt
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        uses: actions/checkout@v5
      - id: setup-jdk
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - run: chmod +x gradlew
      - run: ./gradlew detekt

  build:
    name: Build code base
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        uses: actions/checkout@v5
      - id: setup-jdk
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - run: chmod +x gradlew
      - run: ./gradlew build
