name: Verify Codebase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Check code base with ktlint
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: github/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: NOTICE
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_KOTLIN: true

  detekt:
    name: Check code base with detekt
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        uses: actions/checkout@v5
      - id: setup-jdk
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - run: chmod +x gradlew
      - run: ./gradlew detekt

  build:
    name: Build code base
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        uses: actions/checkout@v5
      - id: setup-jdk
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - run: chmod +x gradlew
      - run: ./gradlew build
